### ISSUE TITLE
Fix download buttons on the website

### ISSUE THREAD

**Issue by mianzg** [openwashdata/wasteskipsblantyre#6]
The download button are referring to the wrong links now.

Once links are fixed, the csv file will pop up in a browser instead of being downloaded. 

Potential solutions:
1. <a href="https://raw.githubusercontent.com/yourusername/yourrepo/main/path/to/yourfile.csv" download>Download CSV file</a>

**Comment by larnsce** [comment]
Thanks for the suggestion. I will try it here with the wasteskipsblantyre data:

1. <a href="https://raw.githubusercontent.com/openwashdata/wasteskipsblantyre/main/inst/extdata/wasteskipsblantyre.csv" download>Download CSV file</a>

It will still open the CSV in the browser. 

What works is:

- Right click -> Save Link As -> Save locally with .csv ending
